//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 12.0.21005.1
// 
namespace Client.Store.CardServerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/", ConfigurationName="CardServerService.CardService")]
    public interface CardService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cardserver.pa.krumholt.fh.trier.de/CardService/GetUserCertificateR" +
            "equest", ReplyAction="http://service.cardserver.pa.krumholt.fh.trier.de/CardService/GetUserCertificateR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Client.Store.CardServerService.GetUserCertificateResponse> GetUserCertificateAsync(Client.Store.CardServerService.GetUserCertificateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cardserver.pa.krumholt.fh.trier.de/CardService/GetServerCertificat" +
            "eRequest", ReplyAction="http://service.cardserver.pa.krumholt.fh.trier.de/CardService/GetServerCertificat" +
            "eResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Client.Store.CardServerService.GetServerCertificateResponse> GetServerCertificateAsync(Client.Store.CardServerService.GetServerCertificateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cardserver.pa.krumholt.fh.trier.de/CardService/GetCardDataRequest", ReplyAction="http://service.cardserver.pa.krumholt.fh.trier.de/CardService/GetCardDataResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Client.Store.CardServerService.GetCardDataResponse> GetCardDataAsync(Client.Store.CardServerService.GetCardDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cardserver.pa.krumholt.fh.trier.de/CardService/CreateAccountReques" +
            "t", ReplyAction="http://service.cardserver.pa.krumholt.fh.trier.de/CardService/CreateAccountRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Client.Store.CardServerService.CreateAccountResponse> CreateAccountAsync(Client.Store.CardServerService.CreateAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cardserver.pa.krumholt.fh.trier.de/CardService/GetAliasRequest", ReplyAction="http://service.cardserver.pa.krumholt.fh.trier.de/CardService/GetAliasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Client.Store.CardServerService.GetAliasResponse> GetAliasAsync(Client.Store.CardServerService.GetAliasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cardserver.pa.krumholt.fh.trier.de/CardService/DeleteAccountReques" +
            "t", ReplyAction="http://service.cardserver.pa.krumholt.fh.trier.de/CardService/DeleteAccountRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Client.Store.CardServerService.DeleteAccountResponse> DeleteAccountAsync(Client.Store.CardServerService.DeleteAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cardserver.pa.krumholt.fh.trier.de/CardService/GetUserIdRequest", ReplyAction="http://service.cardserver.pa.krumholt.fh.trier.de/CardService/GetUserIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Client.Store.CardServerService.GetUserIdResponse> GetUserIdAsync(Client.Store.CardServerService.GetUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cardserver.pa.krumholt.fh.trier.de/CardService/GetCardRequest", ReplyAction="http://service.cardserver.pa.krumholt.fh.trier.de/CardService/GetCardResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Client.Store.CardServerService.GetCardResponse> GetCardAsync(Client.Store.CardServerService.GetCardRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/")]
    public partial class credentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/")]
    public partial class card : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private cardDataId cardDataIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cardDataId CardDataId {
            get {
                return this.cardDataIdField;
            }
            set {
                this.cardDataIdField = value;
                this.RaisePropertyChanged("CardDataId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/")]
    public partial class cardDataId : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int editionField;
        
        private int numberField;
        
        private int revisionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Edition {
            get {
                return this.editionField;
            }
            set {
                this.editionField = value;
                this.RaisePropertyChanged("Edition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int Revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
                this.RaisePropertyChanged("Revision");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/")]
    public partial class cardData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private cardDataId cardDataIdField;
        
        private cardDataEntry[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public cardDataId CardDataId {
            get {
                return this.cardDataIdField;
            }
            set {
                this.cardDataIdField = value;
                this.RaisePropertyChanged("CardDataId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public cardDataEntry[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/")]
    public partial class cardDataEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/")]
    public partial class key : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] modulusField;
        
        private byte[] exponentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] Modulus {
            get {
                return this.modulusField;
            }
            set {
                this.modulusField = value;
                this.RaisePropertyChanged("Modulus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] Exponent {
            get {
                return this.exponentField;
            }
            set {
                this.exponentField = value;
                this.RaisePropertyChanged("Exponent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/")]
    public partial class signature : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string signeeIdField;
        
        private byte[] signatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SigneeId {
            get {
                return this.signeeIdField;
            }
            set {
                this.signeeIdField = value;
                this.RaisePropertyChanged("SigneeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("Signature");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/")]
    public partial class certificate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string certificateIdField;
        
        private signature signatureField;
        
        private key publicKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CertificateId {
            get {
                return this.certificateIdField;
            }
            set {
                this.certificateIdField = value;
                this.RaisePropertyChanged("CertificateId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public signature Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("Signature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public key PublicKey {
            get {
                return this.publicKeyField;
            }
            set {
                this.publicKeyField = value;
                this.RaisePropertyChanged("PublicKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserCertificate", WrapperNamespace="http://service.cardserver.pa.krumholt.fh.trier.de/", IsWrapped=true)]
    public partial class GetUserCertificateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Client.Store.CardServerService.credentials arg0;
        
        public GetUserCertificateRequest() {
        }
        
        public GetUserCertificateRequest(Client.Store.CardServerService.credentials arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserCertificateResponse", WrapperNamespace="http://service.cardserver.pa.krumholt.fh.trier.de/", IsWrapped=true)]
    public partial class GetUserCertificateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Client.Store.CardServerService.certificate @return;
        
        public GetUserCertificateResponse() {
        }
        
        public GetUserCertificateResponse(Client.Store.CardServerService.certificate @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServerCertificate", WrapperNamespace="http://service.cardserver.pa.krumholt.fh.trier.de/", IsWrapped=true)]
    public partial class GetServerCertificateRequest {
        
        public GetServerCertificateRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServerCertificateResponse", WrapperNamespace="http://service.cardserver.pa.krumholt.fh.trier.de/", IsWrapped=true)]
    public partial class GetServerCertificateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Client.Store.CardServerService.certificate @return;
        
        public GetServerCertificateResponse() {
        }
        
        public GetServerCertificateResponse(Client.Store.CardServerService.certificate @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCardData", WrapperNamespace="http://service.cardserver.pa.krumholt.fh.trier.de/", IsWrapped=true)]
    public partial class GetCardDataRequest {
        
        public GetCardDataRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCardDataResponse", WrapperNamespace="http://service.cardserver.pa.krumholt.fh.trier.de/", IsWrapped=true)]
    public partial class GetCardDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Client.Store.CardServerService.cardData @return;
        
        public GetCardDataResponse() {
        }
        
        public GetCardDataResponse(Client.Store.CardServerService.cardData @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAccount", WrapperNamespace="http://service.cardserver.pa.krumholt.fh.trier.de/", IsWrapped=true)]
    public partial class CreateAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwordHash;
        
        public CreateAccountRequest() {
        }
        
        public CreateAccountRequest(string email, string passwordHash) {
            this.email = email;
            this.passwordHash = passwordHash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAccountResponse", WrapperNamespace="http://service.cardserver.pa.krumholt.fh.trier.de/", IsWrapped=true)]
    public partial class CreateAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public CreateAccountResponse() {
        }
        
        public CreateAccountResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAlias", WrapperNamespace="http://service.cardserver.pa.krumholt.fh.trier.de/", IsWrapped=true)]
    public partial class GetAliasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public GetAliasRequest() {
        }
        
        public GetAliasRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAliasResponse", WrapperNamespace="http://service.cardserver.pa.krumholt.fh.trier.de/", IsWrapped=true)]
    public partial class GetAliasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public GetAliasResponse() {
        }
        
        public GetAliasResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteAccount", WrapperNamespace="http://service.cardserver.pa.krumholt.fh.trier.de/", IsWrapped=true)]
    public partial class DeleteAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Client.Store.CardServerService.credentials arg0;
        
        public DeleteAccountRequest() {
        }
        
        public DeleteAccountRequest(Client.Store.CardServerService.credentials arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteAccountResponse", WrapperNamespace="http://service.cardserver.pa.krumholt.fh.trier.de/", IsWrapped=true)]
    public partial class DeleteAccountResponse {
        
        public DeleteAccountResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserId", WrapperNamespace="http://service.cardserver.pa.krumholt.fh.trier.de/", IsWrapped=true)]
    public partial class GetUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Client.Store.CardServerService.credentials arg0;
        
        public GetUserIdRequest() {
        }
        
        public GetUserIdRequest(Client.Store.CardServerService.credentials arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserIdResponse", WrapperNamespace="http://service.cardserver.pa.krumholt.fh.trier.de/", IsWrapped=true)]
    public partial class GetUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public GetUserIdResponse() {
        }
        
        public GetUserIdResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCard", WrapperNamespace="http://service.cardserver.pa.krumholt.fh.trier.de/", IsWrapped=true)]
    public partial class GetCardRequest {
        
        public GetCardRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCardResponse", WrapperNamespace="http://service.cardserver.pa.krumholt.fh.trier.de/", IsWrapped=true)]
    public partial class GetCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cardserver.pa.krumholt.fh.trier.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Client.Store.CardServerService.card @return;
        
        public GetCardResponse() {
        }
        
        public GetCardResponse(Client.Store.CardServerService.card @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CardServiceChannel : Client.Store.CardServerService.CardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CardServiceClient : System.ServiceModel.ClientBase<Client.Store.CardServerService.CardService>, Client.Store.CardServerService.CardService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CardServiceClient() : 
                base(CardServiceClient.GetDefaultBinding(), CardServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.CardServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CardServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CardServiceClient.GetBindingForEndpoint(endpointConfiguration), CardServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CardServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CardServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CardServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CardServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Store.CardServerService.GetUserCertificateResponse> Client.Store.CardServerService.CardService.GetUserCertificateAsync(Client.Store.CardServerService.GetUserCertificateRequest request) {
            return base.Channel.GetUserCertificateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Store.CardServerService.GetUserCertificateResponse> GetUserCertificateAsync(Client.Store.CardServerService.credentials arg0) {
            Client.Store.CardServerService.GetUserCertificateRequest inValue = new Client.Store.CardServerService.GetUserCertificateRequest();
            inValue.arg0 = arg0;
            return ((Client.Store.CardServerService.CardService)(this)).GetUserCertificateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Store.CardServerService.GetServerCertificateResponse> Client.Store.CardServerService.CardService.GetServerCertificateAsync(Client.Store.CardServerService.GetServerCertificateRequest request) {
            return base.Channel.GetServerCertificateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Store.CardServerService.GetServerCertificateResponse> GetServerCertificateAsync() {
            Client.Store.CardServerService.GetServerCertificateRequest inValue = new Client.Store.CardServerService.GetServerCertificateRequest();
            return ((Client.Store.CardServerService.CardService)(this)).GetServerCertificateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Store.CardServerService.GetCardDataResponse> Client.Store.CardServerService.CardService.GetCardDataAsync(Client.Store.CardServerService.GetCardDataRequest request) {
            return base.Channel.GetCardDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Store.CardServerService.GetCardDataResponse> GetCardDataAsync() {
            Client.Store.CardServerService.GetCardDataRequest inValue = new Client.Store.CardServerService.GetCardDataRequest();
            return ((Client.Store.CardServerService.CardService)(this)).GetCardDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Store.CardServerService.CreateAccountResponse> Client.Store.CardServerService.CardService.CreateAccountAsync(Client.Store.CardServerService.CreateAccountRequest request) {
            return base.Channel.CreateAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Store.CardServerService.CreateAccountResponse> CreateAccountAsync(string email, string passwordHash) {
            Client.Store.CardServerService.CreateAccountRequest inValue = new Client.Store.CardServerService.CreateAccountRequest();
            inValue.email = email;
            inValue.passwordHash = passwordHash;
            return ((Client.Store.CardServerService.CardService)(this)).CreateAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Store.CardServerService.GetAliasResponse> Client.Store.CardServerService.CardService.GetAliasAsync(Client.Store.CardServerService.GetAliasRequest request) {
            return base.Channel.GetAliasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Store.CardServerService.GetAliasResponse> GetAliasAsync(string arg0) {
            Client.Store.CardServerService.GetAliasRequest inValue = new Client.Store.CardServerService.GetAliasRequest();
            inValue.arg0 = arg0;
            return ((Client.Store.CardServerService.CardService)(this)).GetAliasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Store.CardServerService.DeleteAccountResponse> Client.Store.CardServerService.CardService.DeleteAccountAsync(Client.Store.CardServerService.DeleteAccountRequest request) {
            return base.Channel.DeleteAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Store.CardServerService.DeleteAccountResponse> DeleteAccountAsync(Client.Store.CardServerService.credentials arg0) {
            Client.Store.CardServerService.DeleteAccountRequest inValue = new Client.Store.CardServerService.DeleteAccountRequest();
            inValue.arg0 = arg0;
            return ((Client.Store.CardServerService.CardService)(this)).DeleteAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Store.CardServerService.GetUserIdResponse> Client.Store.CardServerService.CardService.GetUserIdAsync(Client.Store.CardServerService.GetUserIdRequest request) {
            return base.Channel.GetUserIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Store.CardServerService.GetUserIdResponse> GetUserIdAsync(Client.Store.CardServerService.credentials arg0) {
            Client.Store.CardServerService.GetUserIdRequest inValue = new Client.Store.CardServerService.GetUserIdRequest();
            inValue.arg0 = arg0;
            return ((Client.Store.CardServerService.CardService)(this)).GetUserIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Store.CardServerService.GetCardResponse> Client.Store.CardServerService.CardService.GetCardAsync(Client.Store.CardServerService.GetCardRequest request) {
            return base.Channel.GetCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Store.CardServerService.GetCardResponse> GetCardAsync() {
            Client.Store.CardServerService.GetCardRequest inValue = new Client.Store.CardServerService.GetCardRequest();
            return ((Client.Store.CardServerService.CardService)(this)).GetCardAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.CardServicePort)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.CardServicePort)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:9999/cardserver");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return CardServiceClient.GetBindingForEndpoint(EndpointConfiguration.CardServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return CardServiceClient.GetEndpointAddress(EndpointConfiguration.CardServicePort);
        }
        
        public enum EndpointConfiguration {
            
            CardServicePort,
        }
    }
}
