//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Xml.XmlDocument.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create node of type {0}..
        /// </summary>
        internal static string Arg_CannotCreateNode {
            get {
                return ResourceManager.GetString("Arg_CannotCreateNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XmlReader passed in to construct this XmlValidatingReaderImpl must be an instance of a System.Xml.XmlTextReader..
        /// </summary>
        internal static string Arg_ExpectingXmlTextReader {
            get {
                return ResourceManager.GetString("Arg_ExpectingXmlTextReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is incompatible..
        /// </summary>
        internal static string Arg_IncompatibleParamType {
            get {
                return ResourceManager.GetString("Arg_IncompatibleParamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration has already finished..
        /// </summary>
        internal static string Sch_EnumFinished {
            get {
                return ResourceManager.GetString("Sch_EnumFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration has not started. Call MoveNext..
        /// </summary>
        internal static string Sch_EnumNotStarted {
            get {
                return ResourceManager.GetString("Sch_EnumNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare &apos;{0}&apos; and &apos;{1}&apos;..
        /// </summary>
        internal static string Sch_XsdDateTimeCompare {
            get {
                return ResourceManager.GetString("Sch_XsdDateTimeCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Attribute&apos; node cannot be inserted because it is already an attribute of another element..
        /// </summary>
        internal static string Xdom_Attr_InUse {
            get {
                return ResourceManager.GetString("Xdom_Attr_InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute local name cannot be empty..
        /// </summary>
        internal static string Xdom_Attr_Name {
            get {
                return ResourceManager.GetString("Xdom_Attr_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace declaration attribute has an incorrect &apos;namespaceURI&apos;: &apos;{0}&apos;..
        /// </summary>
        internal static string Xdom_Attr_Reserved_XmlNS {
            get {
                return ResourceManager.GetString("Xdom_Attr_Reserved_XmlNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference node must be a child of the current node..
        /// </summary>
        internal static string Xdom_AttrCol_Insert {
            get {
                return ResourceManager.GetString("Xdom_AttrCol_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An &apos;Attributes&apos; collection can only contain &apos;Attribute&apos; objects..
        /// </summary>
        internal static string Xdom_AttrCol_Object {
            get {
                return ResourceManager.GetString("Xdom_AttrCol_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;InnerText&apos; of a &apos;Document&apos; node is read-only and cannot be set..
        /// </summary>
        internal static string Xdom_Document_Innertext {
            get {
                return ResourceManager.GetString("Xdom_Document_Innertext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document already has an &apos;XmlDeclaration&apos; node..
        /// </summary>
        internal static string Xdom_DualDeclarationNode {
            get {
                return ResourceManager.GetString("Xdom_DualDeclarationNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document already has a &apos;DocumentElement&apos; node..
        /// </summary>
        internal static string Xdom_DualDocumentElementNode {
            get {
                return ResourceManager.GetString("Xdom_DualDocumentElementNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document already has a &apos;DocumentType&apos; node..
        /// </summary>
        internal static string Xdom_DualDocumentTypeNode {
            get {
                return ResourceManager.GetString("Xdom_DualDocumentTypeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prefix of an element name cannot start with &apos;xml&apos;..
        /// </summary>
        internal static string Xdom_Ele_Prefix {
            get {
                return ResourceManager.GetString("Xdom_Ele_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local name for elements or attributes cannot be null or an empty string..
        /// </summary>
        internal static string Xdom_Empty_LocalName {
            get {
                return ResourceManager.GetString("Xdom_Empty_LocalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;InnerText&apos; of an &apos;Entity&apos; node is read-only and cannot be set..
        /// </summary>
        internal static string Xdom_Ent_Innertext {
            get {
                return ResourceManager.GetString("Xdom_Ent_Innertext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;EntityReference&apos; nodes have no support for setting value..
        /// </summary>
        internal static string Xdom_EntRef_SetVal {
            get {
                return ResourceManager.GetString("Xdom_EntRef_SetVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element list has changed. The enumeration operation failed to continue..
        /// </summary>
        internal static string Xdom_Enum_ElementList {
            get {
                return ResourceManager.GetString("Xdom_Enum_ElementList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot import nodes of type &apos;{0}&apos;..
        /// </summary>
        internal static string Xdom_Import {
            get {
                return ResourceManager.GetString("Xdom_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot import a null node..
        /// </summary>
        internal static string Xdom_Import_NullNode {
            get {
                return ResourceManager.GetString("Xdom_Import_NullNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index being passed in is out of range..
        /// </summary>
        internal static string Xdom_IndexOutOfRange {
            get {
                return ResourceManager.GetString("Xdom_IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not represent any &apos;XmlNodeType&apos;..
        /// </summary>
        internal static string Xdom_Invalid_NT_String {
            get {
                return ResourceManager.GetString("Xdom_Invalid_NT_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create an &apos;EntityReference&apos; node with a name starting with &apos;#&apos;..
        /// </summary>
        internal static string Xdom_InvalidCharacter_EntityReference {
            get {
                return ResourceManager.GetString("Xdom_InvalidCharacter_EntityReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document to be loaded could not be found..
        /// </summary>
        internal static string Xdom_Load_NoDocument {
            get {
                return ResourceManager.GetString("Xdom_Load_NoDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no reader from which to load the document..
        /// </summary>
        internal static string Xdom_Load_NoReader {
            get {
                return ResourceManager.GetString("Xdom_Load_NoReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The named node is from a different document context..
        /// </summary>
        internal static string Xdom_NamedNode_Context {
            get {
                return ResourceManager.GetString("Xdom_NamedNode_Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Entity&apos; and &apos;Notation&apos; nodes cannot be cloned..
        /// </summary>
        internal static string Xdom_Node_Cloning {
            get {
                return ResourceManager.GetString("Xdom_Node_Cloning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert a node or any ancestor of that node as a child of itself..
        /// </summary>
        internal static string Xdom_Node_Insert_Child {
            get {
                return ResourceManager.GetString("Xdom_Node_Insert_Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current node cannot contain other nodes..
        /// </summary>
        internal static string Xdom_Node_Insert_Contain {
            get {
                return ResourceManager.GetString("Xdom_Node_Insert_Contain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node to be inserted is from a different document context..
        /// </summary>
        internal static string Xdom_Node_Insert_Context {
            get {
                return ResourceManager.GetString("Xdom_Node_Insert_Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert the node in the specified location..
        /// </summary>
        internal static string Xdom_Node_Insert_Location {
            get {
                return ResourceManager.GetString("Xdom_Node_Insert_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference node is not a child of this node..
        /// </summary>
        internal static string Xdom_Node_Insert_Path {
            get {
                return ResourceManager.GetString("Xdom_Node_Insert_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified node cannot be inserted as the valid child of this node, because the specified node is the wrong type..
        /// </summary>
        internal static string Xdom_Node_Insert_TypeConflict {
            get {
                return ResourceManager.GetString("Xdom_Node_Insert_TypeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This node is read-only. It cannot be modified..
        /// </summary>
        internal static string Xdom_Node_Modify_ReadOnly {
            get {
                return ResourceManager.GetString("Xdom_Node_Modify_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a node without an owner document..
        /// </summary>
        internal static string Xdom_Node_Null_Doc {
            get {
                return ResourceManager.GetString("Xdom_Node_Null_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node to be removed is not a child of this node..
        /// </summary>
        internal static string Xdom_Node_Remove_Child {
            get {
                return ResourceManager.GetString("Xdom_Node_Remove_Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current node cannot contain other nodes, so the node to be removed is not its child..
        /// </summary>
        internal static string Xdom_Node_Remove_Contain {
            get {
                return ResourceManager.GetString("Xdom_Node_Remove_Contain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set a value on node type &apos;{0}&apos;..
        /// </summary>
        internal static string Xdom_Node_SetVal {
            get {
                return ResourceManager.GetString("Xdom_Node_SetVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document does not have a root element..
        /// </summary>
        internal static string Xdom_NoRootEle {
            get {
                return ResourceManager.GetString("Xdom_NoRootEle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the &apos;InnerXml&apos; for the current node because it is either read-only or cannot have children..
        /// </summary>
        internal static string Xdom_Set_InnerXml {
            get {
                return ResourceManager.GetString("Xdom_Set_InnerXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong value for the XML declaration standalone attribute of &apos;{0}&apos;..
        /// </summary>
        internal static string Xdom_standalone {
            get {
                return ResourceManager.GetString("Xdom_standalone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Text&apos; node is not connected in the DOM live tree. No &apos;SplitText&apos; operation could be performed..
        /// </summary>
        internal static string Xdom_TextNode_SplitText {
            get {
                return ResourceManager.GetString("Xdom_TextNode_SplitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong XML version information. The XML must match production &quot;VersionNum ::= &apos;1.&apos; [0-9]+&quot;..
        /// </summary>
        internal static string Xdom_Version {
            get {
                return ResourceManager.GetString("Xdom_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string for white space contains an invalid character..
        /// </summary>
        internal static string Xdom_WS_Char {
            get {
                return ResourceManager.GetString("Xdom_WS_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; character, hexadecimal value {1}, cannot be included in a name..
        /// </summary>
        internal static string Xml_BadNameChar {
            get {
                return ResourceManager.GetString("Xml_BadNameChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot begin with the &apos;{0}&apos; character, hexadecimal value {1}..
        /// </summary>
        internal static string Xml_BadStartNameChar {
            get {
                return ResourceManager.GetString("Xml_BadStartNameChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot bind to the reserved namespace..
        /// </summary>
        internal static string Xml_CanNotBindToReservedNamespace {
            get {
                return ResourceManager.GetString("Xml_CanNotBindToReservedNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteStartDocument cannot be called on writers created with ConformanceLevel.Fragment..
        /// </summary>
        internal static string Xml_CannotStartDocumentOnFragment {
            get {
                return ResourceManager.GetString("Xml_CannotStartDocumentOnFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write XML declaration. XML declaration can be only at the beginning of the document..
        /// </summary>
        internal static string Xml_CannotWriteXmlDecl {
            get {
                return ResourceManager.GetString("Xml_CannotWriteXmlDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Writer is closed..
        /// </summary>
        internal static string Xml_Closed {
            get {
                return ResourceManager.GetString("Xml_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Writer is closed or in error state..
        /// </summary>
        internal static string Xml_ClosedOrError {
            get {
                return ResourceManager.GetString("Xml_ClosedOrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure that the ConformanceLevel setting is set to ConformanceLevel.Fragment or ConformanceLevel.Auto if you want to write an XML fragment..
        /// </summary>
        internal static string Xml_ConformanceLevelFragment {
            get {
                return ResourceManager.GetString("Xml_ConformanceLevelFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DTD has already been written out..
        /// </summary>
        internal static string Xml_DtdAlreadyWritten {
            get {
                return ResourceManager.GetString("Xml_DtdAlreadyWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTD is not allowed in XML fragments..
        /// </summary>
        internal static string Xml_DtdNotAllowedInFragment {
            get {
                return ResourceManager.GetString("Xml_DtdNotAllowedInFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a duplicate attribute name..
        /// </summary>
        internal static string Xml_DupAttributeName {
            get {
                return ResourceManager.GetString("Xml_DupAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write XML declaration. WriteStartDocument method has already written it..
        /// </summary>
        internal static string Xml_DupXmlDecl {
            get {
                return ResourceManager.GetString("Xml_DupXmlDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The empty string &apos;&apos; is not a valid local name..
        /// </summary>
        internal static string Xml_EmptyLocalName {
            get {
                return ResourceManager.GetString("Xml_EmptyLocalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The empty string &apos;&apos; is not a valid name..
        /// </summary>
        internal static string Xml_EmptyName {
            get {
                return ResourceManager.GetString("Xml_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}, position {1}..
        /// </summary>
        internal static string Xml_ErrorPosition {
            get {
                return ResourceManager.GetString("Xml_ErrorPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid Base64 text sequence..
        /// </summary>
        internal static string Xml_InvalidBase64Value {
            get {
                return ResourceManager.GetString("Xml_InvalidBase64Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid BinHex text sequence..
        /// </summary>
        internal static string Xml_InvalidBinHexValue {
            get {
                return ResourceManager.GetString("Xml_InvalidBinHexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid BinHex text sequence. The sequence must contain an even number of characters..
        /// </summary>
        internal static string Xml_InvalidBinHexValueOddCount {
            get {
                return ResourceManager.GetString("Xml_InvalidBinHexValueOddCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have &apos;]]&gt;&apos; inside an XML CDATA block..
        /// </summary>
        internal static string Xml_InvalidCDataChars {
            get {
                return ResourceManager.GetString("Xml_InvalidCDataChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;, hexadecimal value {1}, is an invalid character..
        /// </summary>
        internal static string Xml_InvalidCharacter {
            get {
                return ResourceManager.GetString("Xml_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An XML comment cannot contain &apos;--&apos;, and &apos;-&apos; cannot be the last character..
        /// </summary>
        internal static string Xml_InvalidCommentChars {
            get {
                return ResourceManager.GetString("Xml_InvalidCommentChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indentation value must be greater than 0..
        /// </summary>
        internal static string Xml_InvalidIndentation {
            get {
                return ResourceManager.GetString("Xml_InvalidIndentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name character in &apos;{0}&apos;..
        /// </summary>
        internal static string Xml_InvalidNameChars {
            get {
                return ResourceManager.GetString("Xml_InvalidNameChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name character in &apos;{0}&apos;. The &apos;{1}&apos; character, hexadecimal value {2}, cannot be included in a name..
        /// </summary>
        internal static string Xml_InvalidNameCharsDetail {
            get {
                return ResourceManager.GetString("Xml_InvalidNameCharsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid XmlNodeType..
        /// </summary>
        internal static string Xml_InvalidNodeType {
            get {
                return ResourceManager.GetString("Xml_InvalidNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is not valid due to the current state of the object..
        /// </summary>
        internal static string Xml_InvalidOperation {
            get {
                return ResourceManager.GetString("Xml_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have &apos;?&gt;&apos; inside an XML processing instruction..
        /// </summary>
        internal static string Xml_InvalidPiChars {
            get {
                return ResourceManager.GetString("Xml_InvalidPiChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid name for processing instructions..
        /// </summary>
        internal static string Xml_InvalidPIName {
            get {
                return ResourceManager.GetString("Xml_InvalidPIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefixes beginning with &quot;xml&quot; (regardless of whether the characters are uppercase, lowercase, or some combination thereof) are reserved for use by XML..
        /// </summary>
        internal static string Xml_InvalidPrefix {
            get {
                return ResourceManager.GetString("Xml_InvalidPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XML attribute quote character. Valid attribute quote characters are &apos; and &quot;..
        /// </summary>
        internal static string Xml_InvalidQuote {
            get {
                return ResourceManager.GetString("Xml_InvalidQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} method is not supported on node type {1}. If you want to read typed content of an element, use the ReadElementContentAs method..
        /// </summary>
        internal static string Xml_InvalidReadContentAs {
            get {
                return ResourceManager.GetString("Xml_InvalidReadContentAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} method is not supported on node type {1}..
        /// </summary>
        internal static string Xml_InvalidReadElementContentAs {
            get {
                return ResourceManager.GetString("Xml_InvalidReadElementContentAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid high surrogate character (0x{0}). A high surrogate character must have a value from range (0xD800 - 0xDBFF)..
        /// </summary>
        internal static string Xml_InvalidSurrogateHighChar {
            get {
                return ResourceManager.GetString("Xml_InvalidSurrogateHighChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The surrogate pair is invalid. Missing a low surrogate character..
        /// </summary>
        internal static string Xml_InvalidSurrogateMissingLowChar {
            get {
                return ResourceManager.GetString("Xml_InvalidSurrogateMissingLowChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The surrogate pair (0x{0}, 0x{1}) is invalid. A high surrogate character (0xD800 - 0xDBFF) must always be paired with a low surrogate character (0xDC00 - 0xDFFF)..
        /// </summary>
        internal static string Xml_InvalidSurrogatePairWithArgs {
            get {
                return ResourceManager.GetString("Xml_InvalidSurrogatePairWithArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid xml:space value..
        /// </summary>
        internal static string Xml_InvalidXmlSpace {
            get {
                return ResourceManager.GetString("Xml_InvalidXmlSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Line {1}, position {2}..
        /// </summary>
        internal static string Xml_MessageWithErrorPosition {
            get {
                return ResourceManager.GetString("Xml_MessageWithErrorPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadContentAsBase64 and ReadContentAsBinHex method calls cannot be mixed with calls to ReadElementContentAsBase64 and ReadElementContentAsBinHex..
        /// </summary>
        internal static string Xml_MixingBinaryContentMethods {
            get {
                return ResourceManager.GetString("Xml_MixingBinaryContentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix &apos;{0}&apos; cannot be mapped to namespace name reserved for &quot;xml&quot; or &quot;xmlns&quot;..
        /// </summary>
        internal static string Xml_NamespaceDeclXmlXmlns {
            get {
                return ResourceManager.GetString("Xml_NamespaceDeclXmlXmlns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the namespace if Namespaces is &apos;false&apos;..
        /// </summary>
        internal static string Xml_NoNamespaces {
            get {
                return ResourceManager.GetString("Xml_NoNamespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only white space characters should be used..
        /// </summary>
        internal static string Xml_NonWhitespace {
            get {
                return ResourceManager.GetString("Xml_NonWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document does not have a root element..
        /// </summary>
        internal static string Xml_NoRoot {
            get {
                return ResourceManager.GetString("Xml_NoRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no XML start tag open..
        /// </summary>
        internal static string Xml_NoStartTag {
            get {
                return ResourceManager.GetString("Xml_NoStartTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotInWriteState..
        /// </summary>
        internal static string Xml_NotInWriteState {
            get {
                return ResourceManager.GetString("Xml_NotInWriteState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteStartDocument needs to be the first call..
        /// </summary>
        internal static string Xml_NotTheFirst {
            get {
                return ResourceManager.GetString("Xml_NotTheFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving of external URIs was prohibited..
        /// </summary>
        internal static string Xml_NullResolver {
            get {
                return ResourceManager.GetString("Xml_NullResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use a prefix with an empty namespace..
        /// </summary>
        internal static string Xml_PrefixForEmptyNs {
            get {
                return ResourceManager.GetString("Xml_PrefixForEmptyNs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prefix &apos;{0}&apos; cannot be redefined from &apos;{1}&apos; to &apos;{2}&apos; within the same start element tag..
        /// </summary>
        internal static string Xml_RedefinePrefix {
            get {
                return ResourceManager.GetString("Xml_RedefinePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative URIs are not supported..
        /// </summary>
        internal static string Xml_RelativeUriNotSupported {
            get {
                return ResourceManager.GetString("Xml_RelativeUriNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second character surrogate pair is not in the input buffer to be written..
        /// </summary>
        internal static string Xml_SurrogatePairSplit {
            get {
                return ResourceManager.GetString("Xml_SurrogatePairSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to undeclared parameter entity &apos;{0}&apos;..
        /// </summary>
        internal static string Xml_UndeclaredParEntity {
            get {
                return ResourceManager.GetString("Xml_UndeclaredParEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; namespace is not defined..
        /// </summary>
        internal static string Xml_UndefNamespace {
            get {
                return ResourceManager.GetString("Xml_UndefNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An undefined prefix is in use..
        /// </summary>
        internal static string Xml_UndefPrefix {
            get {
                return ResourceManager.GetString("Xml_UndefPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected XmlNodeType: &apos;{0}&apos;..
        /// </summary>
        internal static string Xml_UnexpectedNodeType {
            get {
                return ResourceManager.GetString("Xml_UnexpectedNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown resource string: {0}..
        /// </summary>
        internal static string Xml_UnknownResourceString {
            get {
                return ResourceManager.GetString("Xml_UnknownResourceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object type is not supported..
        /// </summary>
        internal static string Xml_UnsupportedClass {
            get {
                return ResourceManager.GetString("Xml_UnsupportedClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlResolver can be set only by fully trusted code..
        /// </summary>
        internal static string Xml_UntrustedCodeSettingResolver {
            get {
                return ResourceManager.GetString("Xml_UntrustedCodeSettingResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token {0} in state {1} would result in an invalid XML document..
        /// </summary>
        internal static string Xml_WrongToken {
            get {
                return ResourceManager.GetString("Xml_WrongToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;xmlns&apos; attribute is bound to the reserved namespace &apos;http://www.w3.org/2000/xmlns/&apos;..
        /// </summary>
        internal static string Xml_XmlnsBelongsToReservedNs {
            get {
                return ResourceManager.GetString("Xml_XmlnsBelongsToReservedNs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix &quot;xmlns&quot; is reserved for use by XML..
        /// </summary>
        internal static string Xml_XmlnsPrefix {
            get {
                return ResourceManager.GetString("Xml_XmlnsPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix &quot;xml&quot; is reserved for use by XML and can be mapped only to namespace name &quot;http://www.w3.org/XML/1998/namespace&quot;..
        /// </summary>
        internal static string Xml_XmlPrefix {
            get {
                return ResourceManager.GetString("Xml_XmlPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A node of type &apos;{0}&apos; cannot have the name &apos;{1}&apos;..
        /// </summary>
        internal static string XmlBadName {
            get {
                return ResourceManager.GetString("XmlBadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &apos;{0}&apos; is not a valid {1} value..
        /// </summary>
        internal static string XmlConvert_BadFormat {
            get {
                return ResourceManager.GetString("XmlConvert_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string was not recognized as a valid Uri..
        /// </summary>
        internal static string XmlConvert_BadUri {
            get {
                return ResourceManager.GetString("XmlConvert_BadUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String must be exactly one character long..
        /// </summary>
        internal static string XmlConvert_NotOneCharString {
            get {
                return ResourceManager.GetString("XmlConvert_NotOneCharString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; was either too large or too small for {1}..
        /// </summary>
        internal static string XmlConvert_Overflow {
            get {
                return ResourceManager.GetString("XmlConvert_Overflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml type &apos;{0}&apos; does not support Clr type &apos;{1}&apos;..
        /// </summary>
        internal static string XmlConvert_TypeBadMapping {
            get {
                return ResourceManager.GetString("XmlConvert_TypeBadMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml type &apos;{0}&apos; does not support a conversion from Clr type &apos;{1}&apos; to Clr type &apos;{2}&apos;..
        /// </summary>
        internal static string XmlConvert_TypeBadMapping2 {
            get {
                return ResourceManager.GetString("XmlConvert_TypeBadMapping2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml type &apos;{0}&apos; cannot convert to Clr type &apos;{1}&apos; unless the source value is a String or an XmlAtomicValue..
        /// </summary>
        internal static string XmlConvert_TypeFromString {
            get {
                return ResourceManager.GetString("XmlConvert_TypeFromString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml type &apos;List of {0}&apos; does not support Clr type &apos;{1}&apos;..
        /// </summary>
        internal static string XmlConvert_TypeListBadMapping {
            get {
                return ResourceManager.GetString("XmlConvert_TypeListBadMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml type &apos;List of {0}&apos; does not support a conversion from Clr type &apos;{1}&apos; to Clr type &apos;{2}&apos;..
        /// </summary>
        internal static string XmlConvert_TypeListBadMapping2 {
            get {
                return ResourceManager.GetString("XmlConvert_TypeListBadMapping2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The String &apos;{0}&apos; cannot be represented as an XmlQualifiedName.  A namespace for prefix &apos;{1}&apos; cannot be found..
        /// </summary>
        internal static string XmlConvert_TypeNoNamespace {
            get {
                return ResourceManager.GetString("XmlConvert_TypeNoNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The QName &apos;{0}&apos; cannot be represented as a String.  A prefix for namespace &apos;{1}&apos; cannot be found..
        /// </summary>
        internal static string XmlConvert_TypeNoPrefix {
            get {
                return ResourceManager.GetString("XmlConvert_TypeNoPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml type &apos;{0}&apos; cannot convert from Clr type &apos;{1}&apos; unless the destination type is String or XmlAtomicValue..
        /// </summary>
        internal static string XmlConvert_TypeToString {
            get {
                return ResourceManager.GetString("XmlConvert_TypeToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A node of type &apos;{0}&apos; cannot have a name..
        /// </summary>
        internal static string XmlNoNameAllowed {
            get {
                return ResourceManager.GetString("XmlNoNameAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-CLS Compliant Exception..
        /// </summary>
        internal static string XmlNonCLSCompliantException {
            get {
                return ResourceManager.GetString("XmlNonCLSCompliantException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace prefix &apos;{0}&apos; is not defined..
        /// </summary>
        internal static string XmlUndefinedAlias {
            get {
                return ResourceManager.GetString("XmlUndefinedAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an invalid object. Only objects returned from Compile() can be passed as input..
        /// </summary>
        internal static string Xp_BadQueryObject {
            get {
                return ResourceManager.GetString("Xp_BadQueryObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;current()&apos; function cannot be used in a pattern..
        /// </summary>
        internal static string Xp_CurrentNotAllowed {
            get {
                return ResourceManager.GetString("Xp_CurrentNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid expression..
        /// </summary>
        internal static string Xp_ExprExpected {
            get {
                return ResourceManager.GetString("Xp_ExprExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}()&apos; has failed..
        /// </summary>
        internal static string Xp_FunctionFailed {
            get {
                return ResourceManager.GetString("Xp_FunctionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument to function &apos;{0}&apos; in &apos;{1}&apos; cannot be converted to a node-set..
        /// </summary>
        internal static string Xp_InvalidArgumentType {
            get {
                return ResourceManager.GetString("Xp_InvalidArgumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid key pattern. It either contains a variable reference or &apos;key()&apos; function..
        /// </summary>
        internal static string Xp_InvalidKeyPattern {
            get {
                return ResourceManager.GetString("Xp_InvalidKeyPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has an invalid qualified name..
        /// </summary>
        internal static string Xp_InvalidName {
            get {
                return ResourceManager.GetString("Xp_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; in &apos;{1}&apos; has an invalid number of arguments..
        /// </summary>
        internal static string Xp_InvalidNumArgs {
            get {
                return ResourceManager.GetString("Xp_InvalidNumArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid XSLT pattern..
        /// </summary>
        internal static string Xp_InvalidPattern {
            get {
                return ResourceManager.GetString("Xp_InvalidPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has an invalid token..
        /// </summary>
        internal static string Xp_InvalidToken {
            get {
                return ResourceManager.GetString("Xp_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace Manager or XsltContext needed. This query has a prefix, variable, or user-defined function..
        /// </summary>
        internal static string Xp_NoContext {
            get {
                return ResourceManager.GetString("Xp_NoContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression must evaluate to a node-set..
        /// </summary>
        internal static string Xp_NodeSetExpected {
            get {
                return ResourceManager.GetString("Xp_NodeSetExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XPath query &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string Xp_NotSupported {
            get {
                return ResourceManager.GetString("Xp_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The xpath query is too complex..
        /// </summary>
        internal static string Xp_QueryTooComplex {
            get {
                return ResourceManager.GetString("Xp_QueryTooComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an unclosed string..
        /// </summary>
        internal static string Xp_UnclosedString {
            get {
                return ResourceManager.GetString("Xp_UnclosedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}()&apos; is undefined..
        /// </summary>
        internal static string Xp_UndefFunc {
            get {
                return ResourceManager.GetString("Xp_UndefFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XsltContext is needed for this query because of an unknown function..
        /// </summary>
        internal static string Xp_UndefinedXsltContext {
            get {
                return ResourceManager.GetString("Xp_UndefinedXsltContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable &apos;{0}&apos; is undefined..
        /// </summary>
        internal static string Xp_UndefVar {
            get {
                return ResourceManager.GetString("Xp_UndefVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is not valid due to the current position of the navigator..
        /// </summary>
        internal static string Xpn_BadPosition {
            get {
                return ResourceManager.GetString("Xpn_BadPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current position of the navigator is missing a valid parent..
        /// </summary>
        internal static string Xpn_MissingParent {
            get {
                return ResourceManager.GetString("Xpn_MissingParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content generated as the result of the operation..
        /// </summary>
        internal static string Xpn_NoContent {
            get {
                return ResourceManager.GetString("Xpn_NoContent", resourceCulture);
            }
        }
    }
}
